import React from 'react';
import { Layout } from 'lucide-react';
import { EncyclopediaIcon, EncyclopediaModel } from './shared';

// ==========================================
// PHASE 0: ENCYCLOPEDIA
// ==========================================

export const Encyclopedia = () => {
    const items = [
        { label: "Public Data (Train)", desc: "Used to train the model.", comp: <EncyclopediaIcon type="train" label="TRAIN" /> },
        { label: "Public Data (Val)", desc: "Held back for local testing.", comp: <EncyclopediaIcon type="test" label="VAL" /> },
        { label: "Submission Data", desc: "New data generated by users.", comp: <EncyclopediaIcon type="raw" label="RAW" /> },
        { label: "Submission Zip", desc: "The final artifact uploaded.", comp: <EncyclopediaIcon type="zip" label="sub.zip" /> },
        { label: "Base Model", desc: "Untrained generic transformer.", comp: <EncyclopediaModel type="base" /> },
        { label: "Tuned Model", desc: "Specialized via fine-tuning.", comp: <EncyclopediaModel type="tuned" /> },
    ];

    return (
        <div className="w-full h-full p-8 overflow-y-auto bg-slate-50/50">
            <div className="text-center mb-8 mt-4">
                <h2 className="text-2xl font-bold text-slate-800 flex items-center justify-center gap-2">
                    <Layout className="text-indigo-500" /> Component Encyclopedia
                </h2>
                <p className="text-slate-400 text-sm mt-2">A visual guide to the elements used in the AI Challenge workflow.</p>
            </div>

            <div className="grid grid-cols-2 gap-4 max-w-2xl mx-auto">
                {items.map((item, idx) => (
                    <div key={idx} className="bg-white border border-slate-100 rounded-xl p-4 flex items-center gap-4 shadow-sm hover:shadow-md transition-shadow">
                        <div className="flex-shrink-0 w-16 flex justify-center">
                            {item.comp}
                        </div>
                        <div className="text-left">
                            <h3 className="font-bold text-slate-700 text-sm">{item.label}</h3>
                            <p className="text-xs text-slate-400 mt-1 leading-snug">{item.desc}</p>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};
